# Generated by Django 4.2.5 on 2023-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
