# Generated by Django 4.2.5 on 2023-09-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'start']},
        ),
    ]
