# Generated by Django 4.2.5 on 2023-09-17 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_attendance_time_in_alter_attendance_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
