# Generated by Django 4.2.5 on 2023-09-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
