# Generated by Django 4.2.5 on 2023-09-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_schedule_id_attendance_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
            preserve_default=False,
        ),
    ]
