# Generated by Django 4.2.5 on 2023-09-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schedule_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time_out',
        ),
    ]
